[package]
name = "multiplayer_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beryllium = "0.13.3"
bytemuck = "1.21.0"
gl = "0.14.0"

[dev-dependencies]
